"""Braintrust-specific constants for the Respan Braintrust instrumentation."""

from respan_sdk.constants.llm_logging import (
    LOG_TYPE_CHAT,
    LOG_TYPE_TASK,
    LOG_TYPE_TOOL,
    LOG_TYPE_WORKFLOW,
)

BRAINTRUST_SPAN_TYPE_LLM = "llm"
BRAINTRUST_SPAN_TYPE_CHAT = "chat"
BRAINTRUST_SPAN_TYPE_TOOL = "tool"
BRAINTRUST_SPAN_TYPE_FUNCTION = "function"
BRAINTRUST_SPAN_TYPE_EVAL = "eval"
BRAINTRUST_SPAN_TYPE_AUTOMATION = "automation"
BRAINTRUST_SPAN_TYPE_TASK = "task"
BRAINTRUST_SPAN_TYPE_SCORE = "score"
BRAINTRUST_SPAN_TYPE_FACET = "facet"
BRAINTRUST_SPAN_TYPE_PREPROCESSOR = "preprocessor"

BRAINTRUST_SPAN_TYPE_TO_LOG_TYPE = {
    BRAINTRUST_SPAN_TYPE_LLM: LOG_TYPE_CHAT,
    BRAINTRUST_SPAN_TYPE_CHAT: LOG_TYPE_CHAT,
    BRAINTRUST_SPAN_TYPE_TOOL: LOG_TYPE_TOOL,
    BRAINTRUST_SPAN_TYPE_FUNCTION: LOG_TYPE_TOOL,
    BRAINTRUST_SPAN_TYPE_EVAL: LOG_TYPE_WORKFLOW,
    BRAINTRUST_SPAN_TYPE_AUTOMATION: LOG_TYPE_WORKFLOW,
    BRAINTRUST_SPAN_TYPE_TASK: LOG_TYPE_TASK,
    BRAINTRUST_SPAN_TYPE_SCORE: LOG_TYPE_TASK,
    BRAINTRUST_SPAN_TYPE_FACET: LOG_TYPE_TASK,
    BRAINTRUST_SPAN_TYPE_PREPROCESSOR: LOG_TYPE_TASK,
}

BRAINTRUST_DEFAULT_SPAN_NAME = "braintrust_span"
BRAINTRUST_ENTITY_PATH = "braintrust"
BRAINTRUST_METADATA_PREFIX = "braintrust_"

