"""Claude Agent SDK native attribute and override constants."""

from respan_sdk.constants.span_attributes import (
    GEN_AI_AGENT_NAME,
    GEN_AI_OPERATION_NAME,
    GEN_AI_TOOL_CALL_ARGUMENTS,
    GEN_AI_TOOL_CALL_RESULT,
    GEN_AI_TOOL_NAME,
    LLM_REQUEST_MODEL,
)


CLAUDE_AGENT_SDK_CONVERSATION_ID_ATTR = "gen_ai.conversation.id"
CLAUDE_AGENT_SDK_RESPONSE_FINISH_REASONS_ATTR = "gen_ai.response.finish_reasons"
CLAUDE_AGENT_SDK_RESPONSE_MODEL_ATTR = "gen_ai.response.model"
CLAUDE_AGENT_SDK_INPUT_MESSAGES_ATTR = "gen_ai.input.messages"
CLAUDE_AGENT_SDK_OUTPUT_MESSAGES_ATTR = "gen_ai.output.messages"
CLAUDE_AGENT_SDK_SYSTEM_INSTRUCTIONS_ATTR = "gen_ai.system_instructions"
CLAUDE_AGENT_SDK_TOOL_DEFINITIONS_ATTR = "gen_ai.tool.definitions"
CLAUDE_AGENT_SDK_TOOL_CALL_ID_ATTR = "gen_ai.tool.call.id"
CLAUDE_AGENT_SDK_USAGE_CACHE_CREATION_INPUT_TOKENS_ATTR = (
    "gen_ai.usage.cache_creation_input_tokens"
)
CLAUDE_AGENT_SDK_USAGE_CACHE_READ_INPUT_TOKENS_ATTR = (
    "gen_ai.usage.cache_read_input_tokens"
)
CLAUDE_AGENT_SDK_USAGE_INPUT_TOKENS_ATTR = "gen_ai.usage.input_tokens"
CLAUDE_AGENT_SDK_USAGE_OUTPUT_TOKENS_ATTR = "gen_ai.usage.output_tokens"
INPUT_VALUE_ATTR = "input.value"
OUTPUT_VALUE_ATTR = "output.value"

RESPAN_OVERRIDE_COMPLETION_TOKENS_ATTR = "completion_tokens"
RESPAN_OVERRIDE_INPUT_ATTR = "input"
RESPAN_OVERRIDE_MODEL_ATTR = "model"
RESPAN_OVERRIDE_OUTPUT_ATTR = "output"
RESPAN_OVERRIDE_TOOL_CALLS_ATTR = "tool_calls"
RESPAN_OVERRIDE_TOOLS_ATTR = "tools"
RESPAN_OVERRIDE_PROMPT_CACHE_CREATION_TOKENS_ATTR = (
    "prompt_cache_creation_tokens"
)
RESPAN_OVERRIDE_PROMPT_CACHE_HIT_TOKENS_ATTR = "prompt_cache_hit_tokens"
RESPAN_OVERRIDE_PROMPT_TOKENS_ATTR = "prompt_tokens"
RESPAN_OVERRIDE_SPAN_TOOLS_ATTR = "span_tools"
RESPAN_OVERRIDE_SPAN_WORKFLOW_NAME_ATTR = "span_workflow_name"
RESPAN_OVERRIDE_TOTAL_REQUEST_TOKENS_ATTR = "total_request_tokens"

CLAUDE_AGENT_SDK_STRIP_ATTRS = frozenset(
    {
        CLAUDE_AGENT_SDK_CONVERSATION_ID_ATTR,
        CLAUDE_AGENT_SDK_INPUT_MESSAGES_ATTR,
        CLAUDE_AGENT_SDK_OUTPUT_MESSAGES_ATTR,
        CLAUDE_AGENT_SDK_RESPONSE_MODEL_ATTR,
        CLAUDE_AGENT_SDK_RESPONSE_FINISH_REASONS_ATTR,
        CLAUDE_AGENT_SDK_SYSTEM_INSTRUCTIONS_ATTR,
        CLAUDE_AGENT_SDK_TOOL_DEFINITIONS_ATTR,
        CLAUDE_AGENT_SDK_USAGE_INPUT_TOKENS_ATTR,
        CLAUDE_AGENT_SDK_USAGE_OUTPUT_TOKENS_ATTR,
        CLAUDE_AGENT_SDK_USAGE_CACHE_READ_INPUT_TOKENS_ATTR,
        CLAUDE_AGENT_SDK_USAGE_CACHE_CREATION_INPUT_TOKENS_ATTR,
        INPUT_VALUE_ATTR,
        OUTPUT_VALUE_ATTR,
        GEN_AI_AGENT_NAME,
        GEN_AI_OPERATION_NAME,
        GEN_AI_TOOL_NAME,
        GEN_AI_TOOL_CALL_ARGUMENTS,
        GEN_AI_TOOL_CALL_RESULT,
        LLM_REQUEST_MODEL,
    }
)
